--unsure where beach is
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514113001,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514113002,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123013,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371033,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371032,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514111012,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491035,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341029,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341030,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341003,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112018,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112022,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514012013,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131028,NULL,'Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291044,'WESTHAVEN','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513131009,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291035,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513131007,'CRANNELL','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513141010,'CRANNELL','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511501001,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042061023,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042061019,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390016,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322015,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514081010,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514015006,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514014001,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515041014,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514013004,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514013005,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514113004,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514113003,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514101006,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514101005,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514121014,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151029,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513101019,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151054,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514022009,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511261025,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311003,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241036,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514061004,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390013,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322027,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322026,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322005,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321049,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390031,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390029,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390033,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513171011,'WESTHAVEN','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121054,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491013,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511301014,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141034,'WESTHAVEN','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514171007,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514154001,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514041003,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134001,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134002,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514131013,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514162008,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042031009,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514124003,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514133006,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514133005,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511501013,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042102052,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514162007,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341009,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514102006,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514102011,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491008,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514015001,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123008,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123009,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514143009,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515321013,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033004,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141066,'WESTHAVEN','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042151012,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042151011,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511301005,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121018,NULL,'Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514012014,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514143013,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514102003,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515091005,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331039,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515192036,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515161013,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033010,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033011,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514015007,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141022,'WESTHAVEN','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322029,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514154006,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514154007,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121047,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514143011,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291047,'TRINIDAD','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491025,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132008,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132007,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514093002,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513141005,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322032,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322031,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513131001,'TRINIDAD','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513121006,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513141001,'CRANNELL','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514013003,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042063027,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514103003,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514103002,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131031,'WESTHAVEN','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515061008,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132005,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132006,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132003,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151007,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515172022,'WESTHAVEN','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511231002,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511231003,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042141021,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331033,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151064,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514012022,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491031,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515361011,'TRINIDAD','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491026,NULL,'Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515041015,'TRINIDAD','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132002,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321050,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513171007,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513151008,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151033,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241032,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151004,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513181019,'WESTHAVEN','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042062003,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042062016,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042062001,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042062002,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514051010,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514012001,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121042,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121041,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151062,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515321006,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515321008,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390025,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515172013,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511271043,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341042,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241035,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491014,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511342010,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511342009,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151042,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491028,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515321014,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042052004,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491007,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515350015,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515350013,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515350014,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514102001,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514102002,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514102008,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514102009,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341001,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390008,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514111015,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371029,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371030,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331006,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511261026,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511501003,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514061006,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514032001,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514052002,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514051006,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514051019,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513181017,'WESTHAVEN','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390004,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033008,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042111007,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390012,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511261013,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033009,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112019,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123014,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131021,NULL,'Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131022,'TRINIDAD','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121050,NULL,'Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121049,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291051,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042141010,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371027,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131008,'TRINIDAD','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514162020,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042102050,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341010,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321044,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515192043,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321004,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491032,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511182009,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241047,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511501004,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515031013,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515031001,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514051005,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511231001,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321010,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511331005,NULL,'Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511301018,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371037,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042131005,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042111008,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241043,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132001,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515191036,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514122026,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491006,NULL,'Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515172019,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141035,'WESTHAVEN','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491004,NULL,'Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491003,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514201083,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514201082,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514124004,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123012,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515092010,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515031015,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033016,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331051,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141037,NULL,'Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321024,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121048,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151041,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341008,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511281067,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042131007,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241048,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141012,NULL,'Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141013,'WESTHAVEN','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042052005,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331012,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511501014,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291047,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134007,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132019,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132018,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341035,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515172020,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514041006,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514041011,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514041010,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134013,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514121012,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132024,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123001,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123002,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514102007,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112005,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514042008,'TRINIDAD','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371015,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513141006,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371025,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515081008,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515092013,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515172031,'WESTHAVEN','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322030,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514091014,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511342008,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515192046,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515192047,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033005,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515061009,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515092011,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514111013,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131018,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321051,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151056,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151055,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515161010,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134014,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291012,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291048,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514021009,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514021001,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042061020,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141071,'WESTHAVEN','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141090,'TRINIDAD','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112002,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514031014,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515350017,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151061,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514021002,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514041002,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514124002,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514061005,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491023,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514122024,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514122025,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514032004,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123006,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123005,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513171012,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513141009,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513151001,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513121001,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513171005,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321031,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131020,'TRINIDAD','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371026,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241071,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514191003,'WESTHAVEN','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515191033,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514061007,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121039,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515031012,'TRINIDAD','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515092016,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511390011,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514171005,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291020,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151051,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511342004,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514021008,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514015002,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514201086,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491017,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291003,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514041009,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514081009,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515081011,'TRINIDAD','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515101009,'TRINIDAD','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042151010,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514022005,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514022008,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042063035,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042063037,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131009,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291002,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291024,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134010,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515101010,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515081009,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291010,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033007,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515111074,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514113005,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514121011,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514121001,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515031014,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514152022,'TRINIDAD','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131015,NULL,'Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121023,NULL,'Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514031004,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514052001,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515061010,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515031009,'TRINIDAD','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033019,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151059,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511261011,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112015,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134006,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134009,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134005,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515172015,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515172023,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491020,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491012,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341028,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341027,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291027,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515101002,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515101007,'TRINIDAD','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491029,NULL,'Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511331018,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511251017,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141087,'WESTHAVEN','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514133003,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515321002,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511501023,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511501024,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151052,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514061013,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514012021,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491009,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514071002,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514011005,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514012005,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151066,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514042005,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141030,'WESTHAVEN','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515172012,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321032,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042063038,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514011012,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515051003,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331047,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151012,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514032009,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241049,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514051011,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042061003,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123004,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291028,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042063019,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331011,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511331015,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322013,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241038,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514051020,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291003,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514092006,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514092007,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511321045,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511331014,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331023,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513181036,'WESTHAVEN','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514041001,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515011047,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515011062,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112003,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511371028,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514092001,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514092010,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514092011,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514092009,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514092002,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514092008,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514091013,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515321007,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141002,'WESTHAVEN','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515011067,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515361010,'TRINIDAD','Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042141016,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151003,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511182005,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514012006,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514031005,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514201089,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514201088,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514123007,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491005,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042051015,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042051014,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042051022,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042051021,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132028,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514131012,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291021,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515350011,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514152021,'TRINIDAD','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515081014,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331010,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112001,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514051009,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511301011,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513171010,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515101008,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491010,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033017,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491036,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511191029,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514122003,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141073,'WESTHAVEN','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515081013,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515101006,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514201062,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511342003,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331005,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331004,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331046,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042051030,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514152023,'TRINIDAD','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514081007,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341004,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291048,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134004,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514134011,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291050,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131034,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491018,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322014,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042061014,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042063034,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141059,NULL,'Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141089,NULL,'Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121035,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042102040,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515121033,'WESTHAVEN','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042051040,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042102039,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042111003,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042131008,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042111009,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042051039,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042051032,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515102004,'TRINIDAD','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513171009,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514171010,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515361009,NULL,'Deadmans Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042061015,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042063036,NULL,'Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042031019,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515161015,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513101018,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131029,NULL,'Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291045,NULL,'Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515161014,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514171009,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112008,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112020,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511251018,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511281066,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511182008,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515350004,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515350012,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515192044,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331027,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331035,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331028,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515192033,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515350006,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331050,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515192038,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515321001,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515350005,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515172025,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311013,NULL,'Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311006,NULL,'Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311021,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311018,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311019,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311009,'TRINIDAD','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311008,NULL,'Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291026,'MCKINLEYVILLE','Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311007,NULL,'Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511291036,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141074,'WESTHAVEN','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141075,'WESTHAVEN','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241022,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515361022,NULL,'Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514033018,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514051021,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514101008,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291002,NULL,'Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515131033,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515291049,'TRINIDAD','Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112014,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514112004,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514111011,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241037,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151063,'TRINIDAD','McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514021003,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514133002,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515341007,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514152017,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515092008,NULL,'Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515141085,NULL,'Luffenholtz Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511301021,'MCKINLEYVILLE','Patrick Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514013010,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514013001,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331045,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491019,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514132030,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515311020,NULL,'McConnahas Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514015005,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514021006,NULL,'Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514133001,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513181014,NULL,'Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514171008,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515061011,'TRINIDAD','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241044,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514013002,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241039,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515151065,'TRINIDAD','Parker Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511182006,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515331049,NULL,'Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514143015,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514143016,'WESTHAVEN','Two Creeks Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (514032002,'WESTHAVEN','Joland Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511231008,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (513171006,NULL,'Little River');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (042061002,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322012,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515322011,'TRINIDAD','Mill Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511241063,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (515361023,'TRINIDAD','Unnamed Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491001,'MCKINLEYVILLE','Strawberry Creek');
INSERT INTO watershed(APN,parcel_city,watershed_name) VALUES (511491002,'MCKINLEYVILLE','Strawberry Creek');